- name: Decky Loader setup
  hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: Check if Decky is already installed
      ansible.builtin.command: test -f /etc/systemd/system/plugin_loader.service
      register: exists 
      ignore_errors: True

    - name: Download Decky install script
      ansible.builtin.get_url:
        url: https://github.com/SteamDeckHomebrew/decky-installer/releases/latest/download/install_release.sh  
        dest: /tmp/decky_install_release.sh
      when: exists is failed
    
    - name: Run Decky install script
      ansible.builtin.shell:
        cmd: cat /tmp/decky_install_release.sh | sh
        creates: /etc/systemd/system/plugin_loader.service
      when: exists is failed
