- name: Wireguard VPN setup
  hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: Install wireguard pacman packages
      community.general.pacman:
        name:
          - wireguard-tools
        state: present

